import type { WishType, WishCase, WishTypeId } from './types';

// 6大愿望类型 + 1个锁定类型
export const wishTypes: WishType[] = [
  { id: 'A', icon: '✉️', color: 'from-amber-400 to-orange-500' },
  { id: 'B', icon: '💬', color: 'from-violet-400 to-purple-600' },
  { id: 'C', icon: '🎂', color: 'from-pink-400 to-rose-500' },
  { id: 'D', icon: '🎨', color: 'from-cyan-400 to-blue-500' },
  { id: 'E', icon: '📖', color: 'from-emerald-400 to-teal-500' },
  { id: 'F', icon: '📸', color: 'from-indigo-400 to-blue-600' },
  { id: 'Z', icon: '💫', color: 'from-gray-400 to-slate-500', locked: true },
];

export function getWishType(id: WishTypeId): WishType | undefined {
  return wishTypes.find((t) => t.id === id);
}

// 已实现的愿望案例（12个基础案例）
export const fulfilledCases: WishCase[] = [
  // A - 给未来的我
  {
    id: 'case-a1',
    type: 'A',
    title: '一年后的自己',
    content: '我希望一年后的自己已经学会了弹吉他，能在朋友聚会上弹一首《故乡》。那时的你，一定比现在的我更勇敢。',
    authorName: '小川',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: '林小枫',
    implementerMessage: '一年后的你，已经在公司年会上弹了《故乡》。感谢那个许愿的自己，你没有放弃。',
    driftPath: 3,
    fulfilledAt: '2026-06-15',
  },
  {
    id: 'case-a2',
    type: 'A',
    title: 'Dear Future Me',
    content: 'I hope by the time you read this, you\'ve finally started that small business you always talked about. You got this!',
    authorName: 'James',
    authorCountry: '🇬🇭 Ghana',
    status: 'fulfilled',
    implementerName: 'Maya',
    implementerMessage: 'Future you did it! The shop opened last month. You were braver than you thought.',
    driftPath: 5,
    fulfilledAt: '2026-06-10',
  },
  // B - 一句来自远方的话
  {
    id: 'case-b1',
    type: 'B',
    title: '度过低谷',
    content: '最近很难熬，希望收到一句能让我撑下去的话。',
    authorName: '匿名旅人',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: '远方的朋友',
    implementerMessage: '黑夜再长，黎明终会到来。你已经很了不起了，别忘了抱抱自己。',
    driftPath: 2,
    fulfilledAt: '2026-06-18',
  },
  {
    id: 'case-b2',
    type: 'B',
    title: 'I Am Enough',
    content: 'I need to hear that I\'m enough just as I am. It\'s been a hard year.',
    authorName: 'Aisha',
    authorCountry: '🇰🇪 Kenya',
    status: 'aiFulfilled',
    implementerName: '灯神',
    implementerMessage: 'You are enough. You always have been. The stars don\'t try to shine brighter — they just do. So do you.',
    driftPath: 15,
    fulfilledAt: '2026-06-12',
  },
  // C - 生日快乐
  {
    id: 'case-c1',
    type: 'C',
    title: '巴黎的生日',
    content: '我最好的朋友明天生日，她一个人在巴黎交换，希望有人能对她说句生日快乐。',
    authorName: '小雨',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: 'Émilie',
    implementerMessage: 'Joyeux anniversaire! 我在塞纳河边给你唱了生日歌，巴黎的晚风也祝你快乐。',
    driftPath: 4,
    fulfilledAt: '2026-06-14',
  },
  {
    id: 'case-c2',
    type: 'C',
    title: 'Birthday in Kenya',
    content: 'My twin brother is volunteering in Kenya for his birthday. Can someone sing him happy birthday?',
    authorName: 'Daniel',
    authorCountry: '🇬🇧 UK',
    status: 'fulfilled',
    implementerName: 'Kwame',
    implementerMessage: 'We sang for him at the village school! The kids made him a card too. Happy birthday, brother!',
    driftPath: 7,
    fulfilledAt: '2026-06-08',
  },
  // D - 画出我的梦想
  {
    id: 'case-d1',
    type: 'D',
    title: '流浪猫救助站',
    content: '我的梦想是开一家流浪猫救助站，让每只猫都有温暖的家。希望有人能帮我画出来。',
    authorName: '猫咪姐姐',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: '画师小鱼',
    implementerMessage: '画好了！一间阳光房，猫咪们躺在窗台上晒太阳，门口挂着"流浪猫之家"的木牌。你的梦想很美。',
    driftPath: 6,
    fulfilledAt: '2026-06-16',
  },
  {
    id: 'case-d2',
    type: 'D',
    title: 'A School for My Village',
    content: 'I dream of building a school in my village in Ghana. Can someone draw what it could look like?',
    authorName: 'Kofi',
    authorCountry: '🇬🇭 Ghana',
    status: 'fulfilled',
    implementerName: 'David',
    implementerMessage: 'Here\'s your school — bright blue walls, a big mango tree for shade, and kids laughing everywhere. Let\'s build it.',
    driftPath: 9,
    fulfilledAt: '2026-06-05',
  },
  // E - 教我一件事
  {
    id: 'case-e1',
    type: 'E',
    title: '红烧肉',
    content: '想学怎么做红烧肉，有人愿意教吗？',
    authorName: '阿杰',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: '张大厨',
    implementerMessage: '记住三个关键：冰糖炒糖色、五花肉焯水、小火慢炖四十分钟。详细菜谱已发你信箱！',
    driftPath: 3,
    fulfilledAt: '2026-06-19',
  },
  {
    id: 'case-e2',
    type: 'E',
    title: 'Thank You in 10 Languages',
    content: 'Teach me how to say "thank you" in 10 languages. I want to travel the world!',
    authorName: 'Lucas',
    authorCountry: '🇧🇷 Brazil',
    status: 'fulfilled',
    implementerName: 'Anna',
    implementerMessage: '谢谢(Xièxie)·Merci·Gracias·Danke·Grazie·Arigatō·Shukran·Spasiba·Kamsahamnida·Obrigado. Now go explore! 🌍',
    driftPath: 5,
    fulfilledAt: '2026-06-11',
  },
  // F - 拍一张照片
  {
    id: 'case-f1',
    type: 'F',
    title: '西藏的星空',
    content: '想看西藏的星空，但身体原因去不了。希望有人能拍给我看。',
    authorName: '星语',
    authorCountry: '🇨🇳 中国',
    status: 'fulfilled',
    implementerName: '高原行者',
    implementerMessage: '在纳木错拍的，海拔4700米，银河就在头顶。这片星空，替你看了。愿你心中也有星河。',
    driftPath: 8,
    fulfilledAt: '2026-06-13',
  },
  {
    id: 'case-f2',
    type: 'F',
    title: 'Northern Lights',
    content: 'Can someone take a photo of the Northern Lights for me? I may never get to see them in person.',
    authorName: 'Emma',
    authorCountry: '🇺🇸 USA',
    status: 'fulfilled',
    implementerName: 'NorthernSoul',
    implementerMessage: 'Captured in Tromsø, Norway at -15°C. The sky danced green and purple for you. Some wishes travel further than light.',
    driftPath: 11,
    fulfilledAt: '2026-06-07',
  },
];

// 即将上线的愿望类型预告
export const comingSoonCases: WishCase[] = [
  {
    id: 'case-g1',
    type: 'A', // 暂时用A，实际是G
    title: '为山区孩子捐书',
    content: '希望为云南山区小学建一个图书角，让每个孩子都能读到课外书。',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
  {
    id: 'case-h1',
    type: 'A',
    title: '梅西签名球衣',
    content: '爸爸是梅西铁粉，他生病了，希望能有一件梅西签名的球衣。',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
  {
    id: 'case-i1',
    type: 'A',
    title: '寻找失散多年的同学',
    content: '想找到小学时最好的朋友，我们已经失联15年了。',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
  {
    id: 'case-j1',
    type: 'A',
    title: '帮我写一段代码',
    content: '需要一段自动整理照片的Python脚本，有人能教我吗？',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
  {
    id: 'case-k1',
    type: 'A',
    title: '西藏旅行搭子',
    content: '一个人不敢去西藏，想找个旅伴一起走318国道。',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
  {
    id: 'case-l1',
    type: 'A',
    title: '自由许愿',
    content: '更多愿望类型，即将解锁...',
    authorName: '预告',
    authorCountry: '🔒',
    status: 'comingSoon',
    driftPath: 0,
  },
];

// 模拟数据：我的愿望
export const myWishes = [
  {
    id: 'my-1',
    type: 'A' as WishTypeId,
    content: '希望半年后的自己已经通过了法语B2考试，能和巴黎的朋友无障碍聊天。',
    status: 'drifting' as const,
    createdAt: '2026-06-20',
    driftCount: 2,
  },
  {
    id: 'my-2',
    type: 'F' as WishTypeId,
    content: '想看极光的照片，这辈子可能没机会亲眼看到了。',
    status: 'received' as const,
    createdAt: '2026-06-18',
    driftCount: 4,
  },
];

// 模拟数据：信箱
export const mailboxWishes = [
  {
    id: 'mb-1',
    type: 'B' as WishTypeId,
    content: '最近工作压力很大，感觉快撑不住了。希望有人能对我说一句鼓励的话。',
    authorName: '远方的旅人',
    authorCountry: '🇨🇳 中国',
    driftedTo: 3,
    createdAt: '2026-06-21',
  },
  {
    id: 'mb-2',
    type: 'E' as WishTypeId,
    content: 'Teach me how to make Chinese dumplings. I love them but never tried making them!',
    authorName: 'Maria',
    authorCountry: '🇵🇹 Portugal',
    driftedTo: 5,
    createdAt: '2026-06-20',
  },
];
